const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const VERSION='0.2.6';
let expression='', currentInput='0', lastExpression='', lastResult=null, lastExplanation=null, currentMode='calc', lang=localStorage.getItem('uc-lang')||'el';
const T={el:{signIn:'Σύνδεση',signOut:'Αποσύνδεση',create:'Δημιουργία λογαριασμού',how:'Πώς;',calc:'Υπολογισμός',fuel:'Καύσιμα',energy:'Ενέργεια',vat:'ΦΠΑ',units:'Μονάδες',history:'Ιστορικό',copy:'Αντιγραφή αποτελέσματος',copied:'Αντιγράφηκε',close:'Κλείσιμο',clearAll:'Διαγραφή όλων',hint:'Δοκίμασε 20 + 25% ή άνοιξε ένα εργαλείο.',username:'Όνομα χρήστη',password:'Κωδικός',continue:'Συνέχεια',finishCreate:'Δημιουργία λογαριασμού',passwordHint:'Τουλάχιστον 8 χαρακτήρες.',noHistory:'Δεν υπάρχουν υπολογισμοί ακόμα.',deleteAllConfirm:'Να διαγραφεί όλο το ιστορικό;',fuelDistance:'Απόσταση (km)',fuelConsumption:'Κατανάλωση (L/100 km)',fuelPrice:'Τιμή καυσίμου / L',calculateFuel:'Υπολόγισε κόστος καυσίμων',energyPower:'Ισχύς (W)',energyHours:'Ώρες / ημέρα',energyDays:'Ημέρες',energyRate:'Τιμή / kWh',calculateEnergy:'Υπολόγισε κόστος ρεύματος',amount:'Ποσό',vatRate:'ΦΠΑ %',addVat:'Πρόσθεσε ΦΠΑ',removeVat:'Αφαίρεσε ΦΠΑ',value:'Τιμή',category:'Κατηγορία',from:'Από',to:'Σε',convert:'Μετατροπή',fuelUsed:'Καύσιμο που χρησιμοποιήθηκε',costPerKm:'Κόστος ανά km',energyUsed:'Ενέργεια',vatAmount:'Ποσό ΦΠΑ',normalSummary:'Ο υπολογιστής εφαρμόζει τη μαθηματική σειρά πράξεων.',percentSummary:p=>`${p}% σημαίνει ${p} στα 100.`,percentOf:p=>`${p}% του`,addIt:'Πρόσθεσέ το',subtractIt:'Αφαίρεσέ το'},en:{signIn:'Sign in',signOut:'Sign out',create:'Create account',how:'How?',calc:'Calc',fuel:'Fuel',energy:'Energy',vat:'VAT',units:'Units',history:'History',copy:'Copy result',copied:'Copied',close:'Close',clearAll:'Clear all',hint:'Try 20 + 25% or open a tool.',username:'Username',password:'Password',continue:'Continue',finishCreate:'Create account',passwordHint:'At least 8 characters.',noHistory:'No calculations yet.',deleteAllConfirm:'Delete all calculation history?',fuelDistance:'Distance (km)',fuelConsumption:'Consumption (L/100 km)',fuelPrice:'Fuel price / L',calculateFuel:'Calculate fuel cost',energyPower:'Power (W)',energyHours:'Hours / day',energyDays:'Days',energyRate:'Price / kWh',calculateEnergy:'Calculate electricity cost',amount:'Amount',vatRate:'VAT %',addVat:'Add VAT',removeVat:'Remove VAT',value:'Value',category:'Category',from:'From',to:'To',convert:'Convert',fuelUsed:'Fuel used',costPerKm:'Cost per km',energyUsed:'Energy',vatAmount:'VAT amount',normalSummary:'The calculator applies normal mathematical order of operations.',percentSummary:p=>`${p}% means ${p} out of every 100.`,percentOf:p=>`${p}% of`,addIt:'Add it',subtractIt:'Subtract it'}};
const t=k=>T[lang][k]??T.en[k]??k, fmt=v=>Number.isFinite(v)?new Intl.NumberFormat(lang==='el'?'el-GR':'en-US',{maximumFractionDigits:10}).format(Math.abs(v)<1e-12?0:v):'Error', esc=v=>String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function updateText(){const set=(id,v)=>{const e=$(id);if(e)e.textContent=v};set('#langButton',lang==='el'?'ΕΛ':'EN');set('#accountButton',t('signIn'));set('#howButton',t('how'));set('#historyButton',t('history'));set('#copyButton',t('copy'));set('#clearHistory',t('clearAll'));set('#closeHow',t('close'));set('#hint',t('hint'));$$('.tab').forEach(b=>set('#'+b.id,t(b.dataset.mode)));set('#version',`v${VERSION}`);set('#footerVersion',`v${VERSION}`);set('#clearButton',clearLabel())}
function setLanguage(){lang=lang==='el'?'en':'el';localStorage.setItem('uc-lang',lang);document.documentElement.lang=lang;updateText();renderTool();renderHistory();renderDisplay();if(lastExplanation&&!$('#howPanel').classList.contains('hidden'))showHow()}
const dbPromise=new Promise((resolve,reject)=>{const r=indexedDB.open('ultimate-calculator',1);r.onupgradeneeded=()=>r.result.createObjectStore('history',{keyPath:'id',autoIncrement:true});r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)});
async function localItems(){try{const d=await dbPromise,s=d.transaction('history').objectStore('history');return await new Promise((ok,no)=>{const r=s.getAll();r.onsuccess=()=>ok(r.result.sort((a,b)=>b.createdAt-a.createdAt));r.onerror=()=>no(r.error)})}catch{return[]}}
async function localAdd(x){const d=await dbPromise;d.transaction('history','readwrite').objectStore('history').add({...x,createdAt:Date.now()})}async function localDelete(id){const d=await dbPromise;d.transaction('history','readwrite').objectStore('history').delete(Number(id))}async function localClear(){const d=await dbPromise;d.transaction('history','readwrite').objectStore('history').clear()}
async function renderHistory(){const items=await localItems(),list=$('#historyList');if(!list)return;list.innerHTML=items.length?items.map(i=>`<div class="history-item"><button class="history-main" data-history="${esc(i.id)}"><div class="history-expression">${esc(i.expression)}</div><div class="history-result">${esc(i.result)}</div></button><button class="history-delete" data-delete="${esc(i.id)}">×</button></div>`).join(''):`<div class="empty">${t('noHistory')}</div>`;$$('[data-history]').forEach(b=>b.onclick=()=>{const x=items.find(i=>String(i.id)===b.dataset.history);if(x){expression=x.expression;currentInput=x.result;lastExpression=x.expression;lastResult=Number(String(x.result).replace(/,/g,''));lastExplanation=x.explanation;currentMode='calc';setModeUI();renderDisplay()}});$$('[data-delete]').forEach(b=>b.onclick=async()=>{await localDelete(b.dataset.delete);renderHistory()})}
async function clearHistory(){if(!confirm(t('deleteAllConfirm')))return;await localClear();renderHistory()}
function evalExpr(s){const a=(s.replace(/,/g,'').match(/(?:\d*\.\d+|\d+\.?\d*|[+\-*/%()])/g)||[]).map(x=>['+','-','*','/','%','(',')'].includes(x)?x:Number(x));let i=0;function p(){if(a[i]==='-'){i++;return-p()}if(a[i]==='('){i++;const v=add();if(a[i]!==')')throw 0;i++;return v}const n=a[i++];if(typeof n!=='number')throw 0;return a[i]==='%'?(i++,n/100):n}function m(){let v=p();while(a[i]==='*'||a[i]==='/'){const o=a[i++],r=p();if(o==='/'&&r===0)throw 0;v=o==='*'?v*r:v/r}return v}function add(){let v=m();while(a[i]==='+'||a[i]==='-'){const o=a[i++],r=m();v=o==='+'?v+r:v-r}return v}const v=add();if(i!==a.length)throw 0;return v}
function makeExplanation(e,v){const m=e.replace(/,/g,'').match(/^(-?[\d.]+)\s*([+-])\s*(\d+(?:\.\d+)?)%$/);if(m){const base=+m[1],p=+m[3],amt=base*p/100;return{summary:t('percentSummary')(p),steps:[{title:t('percentOf')(p),formula:`${fmt(base)} × ${p/100}`,result:fmt(amt)},{title:m[2]==='+'?t('addIt'):t('subtractIt'),formula:`${fmt(base)} ${m[2]} ${fmt(amt)}`,result:fmt(v)}]}}return{summary:t('normalSummary'),steps:[{title:e,formula:e,result:fmt(v)}]}}
function clearLabel(){return expression||lastResult!==null?'C':'AC'}
function renderDisplay(){const ex=$('#expression'),r=$('#result');if(lastResult!==null&&lastExpression===expression){ex.textContent=lastExpression+' =';r.textContent=fmt(lastResult)}else{const pending=expression.match(/(.*?)([+\-*/])$/);if(pending){ex.textContent=pending[1]+' '+pending[2];r.textContent=currentInput||'0'}else{ex.textContent='';r.textContent=currentInput||'0'}}$('#clearButton').textContent=clearLabel();$('#howButton').classList.toggle('hidden',!(lastResult!==null&&lastExpression===expression&&lastExplanation))}
function resetHow(){lastResult=null;lastExplanation=null;lastExpression='';$('#howPanel')?.classList.add('hidden')}
function inputValue(v){resetHow();if(currentInput==='Error')clearAll();if(currentInput==='0'&&v!=='.')currentInput=v;else if(v==='.'&&!currentInput.includes('.'))currentInput+='.';else currentInput+=v;if(/[+\-*/]$/.test(expression)){}else if(expression.endsWith(currentInput.slice(0,-1))){}expression=expression.replace(/(?:\d*\.?\d+%?)$/,'')+currentInput;renderDisplay()}
function operator(v){if(currentInput==='Error')return;resetHow();if(!expression)expression=currentInput;if(/[+\-*/]$/.test(expression))expression=expression.slice(0,-1)+v;else expression+=v;currentInput='0';renderDisplay()}
function percent(){resetHow();if(currentInput==='0'||currentInput==='Error')return;if(!currentInput.endsWith('%')){currentInput+='%';expression=expression.replace(/(?:\d*\.?\d+%?)$/,'')+currentInput}renderDisplay()}
function backspace(){resetHow();if(!expression){currentInput='0'}else{expression=expression.replace(/.$/,'');const m=expression.match(/(?:\d*\.?\d+%?)$/);currentInput=m?m[0]:'0'}renderDisplay()}
function clearCurrent(){resetHow();if(!expression){currentInput='0';return}if(/[+\-*/]$/.test(expression)){expression=expression.slice(0,-1);currentInput=expression.match(/(?:\d*\.?\d+%?)$/)?.[0]||'0'}else{expression=expression.replace(/(?:\d*\.?\d+%?)$/,'');currentInput='0'}renderDisplay()}
function clearAll(){resetHow();expression='';currentInput='0';renderDisplay()}
async function calculate(){if(!expression||/[+\-*/]$/.test(expression))return;try{const v=evalExpr(expression);lastExpression=expression;lastResult=v;lastExplanation=makeExplanation(expression,v);currentInput=fmt(v);await localAdd({expression,result:fmt(v),explanation:lastExplanation});renderDisplay();renderHistory()}catch{currentInput='Error';renderDisplay()}}
function showHow(){if(!lastExplanation)return;$('#howContent').innerHTML=`<p class="how-summary">${esc(lastExplanation.summary)}</p>`+lastExplanation.steps.map(s=>`<div class="how-step"><div class="how-title">${esc(s.title)}</div><div class="how-formula">${esc(s.formula)}</div><div class="how-result">${esc(s.result)}</div></div>`).join('');$('#howPanel').classList.remove('hidden')}
const units={length:{m:1,km:1000,cm:.01,mm:.001,ft:.3048,mi:1609.344},mass:{kg:1,g:.001,lb:.45359237,oz:.0283495231},volume:{l:1,ml:.001,gal:3.785411784},temperature:null};
function renderTool(){const p=$('#toolPanel');if(!p)return;const mode=currentMode;if(mode==='fuel')p.innerHTML=`<div class="tool-grid"><label class="tool-field">${t('fuelDistance')}<input id="fuelD" type="number" inputmode="decimal"></label><label class="tool-field">${t('fuelConsumption')}<input id="fuelC" type="number" inputmode="decimal"></label><label class="tool-field">${t('fuelPrice')}<input id="fuelP" type="number" inputmode="decimal"></label></div><button class="tool-action" id="fuelCalc">${t('calculateFuel')}</button><div id="toolResult" class="tool-result hidden"></div>`;else if(mode==='energy')p.innerHTML=`<div class="tool-grid"><label class="tool-field">${t('energyPower')}<input id="enP" type="number" inputmode="decimal"></label><label class="tool-field">${t('energyHours')}<input id="enH" type="number" inputmode="decimal"></label><label class="tool-field">${t('energyDays')}<input id="enD" type="number" inputmode="decimal" value="30"></label><label class="tool-field">${t('energyRate')}<input id="enR" type="number" inputmode="decimal"></label></div><button class="tool-action" id="energyCalc">${t('calculateEnergy')}</button><div id="toolResult" class="tool-result hidden"></div>`;else if(mode==='vat')p.innerHTML=`<label class="tool-field">${t('amount')}<input id="vatAmountInput" type="number" inputmode="decimal"></label><label class="tool-field">${t('vatRate')}<input id="vatRateInput" type="number" inputmode="decimal" value="24"></label><div class="bottom-actions"><button class="tool-action" id="addVat">${t('addVat')}</button><button class="tool-action" id="removeVat">${t('removeVat')}</button></div><div id="toolResult" class="tool-result hidden"></div>`;else if(mode==='units')p.innerHTML=`<div class="tool-grid"><label class="tool-field">${t('category')}<select id="unitCat"><option value="length">${lang==='el'?'Μήκος':'Length'}</option><option value="mass">${lang==='el'?'Μάζα':'Mass'}</option><option value="volume">${lang==='el'?'Όγκος':'Volume'}</option></select></label><label class="tool-field">${t('value')}<input id="unitVal" type="number" inputmode="decimal"></label><label class="tool-field">${t('from')}<select id="unitFrom"></select></label><label class="tool-field">${t('to')}<select id="unitTo"></select></label></div><button class="tool-action" id="unitCalc">${t('convert')}</button><div id="toolResult" class="tool-result hidden"></div>`;else p.innerHTML='';bindTools()}
function showToolResult(html){const e=$('#toolResult');if(e){e.innerHTML=html;e.classList.remove('hidden')}}
function bindTools(){if($('#fuelCalc'))$('#fuelCalc').onclick=()=>{const d=+$('#fuelD').value,c=+$('#fuelC').value,p=+$('#fuelP').value,u=d*c/100,cost=u*p;showToolResult(`<strong>${fmt(cost)}</strong><br>${t('fuelUsed')}: ${fmt(u)} L<br>${t('costPerKm')}: ${fmt(cost/d)}`)};if($('#energyCalc'))$('#energyCalc').onclick=()=>{const p=+$('#enP').value,h=+$('#enH').value,d=+$('#enD').value,r=+$('#enR').value,k=p/1000*h*d,cost=k*r;showToolResult(`<strong>${fmt(cost)}</strong><br>${t('energyUsed')}: ${fmt(k)} kWh`)};if($('#addVat)){}if($('#addVat'))$('#addVat').onclick=()=>vat(true);if($('#removeVat'))$('#removeVat').onclick=()=>vat(false);if($('#unitCat')){const fill=()=>{const o=units[$('#unitCat').value]||{};['unitFrom','unitTo'].forEach(id=>{$('#'+id).innerHTML=Object.keys(o).map(k=>`<option value="${k}">${k}</option>`).join('')})};$('#unitCat').onchange=fill;fill();$('#unitCalc').onclick=()=>{const cat=$('#unitCat').value,v=+$('#unitVal').value,f=$('#unitFrom').value,to=$('#unitTo').value;let out;if(cat==='temperature'){out=v}else{const o=units[cat];out=v*o[f]/o[to]}showToolResult(`<strong>${fmt(out)}</strong> ${to}`)}}}
function vat(add){const a=+$('#vatAmountInput').value,r=+$('#vatRateInput').value;if(!Number.isFinite(a)||!Number.isFinite(r))return;const tax=add?a*r/100:a-a/(1+r/100);const total=add?a+tax:a-tax;showToolResult(`<strong>${fmt(total)}</strong><br>${t('vatAmount')}: ${fmt(tax)}`)}
function setModeUI(){const calc=currentMode==='calc';$('#calculatorDisplay')?.classList.toggle('hidden',!calc);$('#keypad')?.classList.toggle('hidden',!calc);$('#toolPanel')?.classList.toggle('hidden',calc);$$('.tab').forEach(b=>b.classList.toggle('active',b.dataset.mode===currentMode));if(!calc){$('#howPanel')?.classList.add('hidden');renderTool()}}
function switchMode(m){currentMode=m;setModeUI()}
function copyResult(){if(lastResult===null)return;navigator.clipboard?.writeText(fmt(lastResult));const b=$('#copyButton');if(b){b.textContent=t('copied');setTimeout(()=>b.textContent=t('copy'),1200)}}
$$('.key').forEach(b=>b.onclick=()=>{const a=b.dataset.action,v=b.dataset.value;if(a==='equals')calculate();else if(a==='backspace')backspace();else if(a==='clear')clearCurrent();else if(v==='%')percent();else if(['+','-','*','/'].includes(v))operator(v);else if(v)inputValue(v)});
$$('.tab').forEach(b=>b.onclick=()=>switchMode(b.dataset.mode));
$('#howButton')?.addEventListener('click',showHow);$('#closeHow')?.addEventListener('click',()=>$('#howPanel').classList.add('hidden'));$('#historyButton')?.addEventListener('click',()=>$('#historyPanel').classList.toggle('hidden'));$('#clearHistory')?.addEventListener('click',clearHistory);$('#copyButton')?.addEventListener('click',copyResult);$('#langButton')?.addEventListener('click',setLanguage);
$('#themeButton')?.addEventListener('click',()=>document.body.classList.toggle('light'));
window.addEventListener('keydown',e=>{if(currentMode!=='calc')return;if(/\d/.test(e.key)||e.key==='.')inputValue(e.key);else if(['+','-','*','/'].includes(e.key))operator(e.key);else if(e.key==='%')percent();else if(e.key==='Backspace')backspace();else if(e.key==='Escape')clearCurrent();else if(e.key==='Enter'||e.key==='=')calculate()});
updateText();renderDisplay();renderHistory();setModeUI();
