const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const VERSION='0.3.0';
let lang=localStorage.getItem('uc-lang')||'el';
let mode='calc', expression='', current='', justCalculated=false, lastExpression='', lastResult=null, howData=null;
const T={el:{calc:'Υπολογισμός',fuel:'Καύσιμα',energy:'Ενέργεια',vat:'ΦΠΑ',units:'Μονάδες',how:'Πώς υπολογίστηκε',history:'Ιστορικό',copy:'Αντιγραφή αποτελέσματος',copied:'Αντιγράφηκε',clear:'Διαγραφή όλων',confirm:'Διαγραφή όλου του ιστορικού;',confirmYes:'Διαγραφή',none:'Δεν υπάρχουν υπολογισμοί ακόμη.',hint:'Πληκτρολόγησε μια πράξη για να ξεκινήσεις.',delete:'Διαγραφή',created:'Δημιουργήθηκε από',fuelD:'Απόσταση (km)',fuelC:'Κατανάλωση (L/100 km)',fuelP:'Τιμή καυσίμου / L',fuelGo:'Υπολογισμός κόστους καυσίμου',fuelUsed:'Καύσιμο που χρησιμοποιήθηκε',costKm:'Κόστος ανά km',energyP:'Ισχύς (W)',energyH:'Ώρες / ημέρα',energyD:'Ημέρες',energyR:'Τιμή / kWh',energyGo:'Υπολογισμός κόστους ρεύματος',energyUsed:'Ενέργεια',amount:'Ποσό',vatRate:'ΦΠΑ %',addVat:'Πρόσθεσε ΦΠΑ',removeVat:'Αφαίρεσε ΦΠΑ',vatAmount:'Ποσό ΦΠΑ',value:'Τιμή',category:'Κατηγορία',from:'Από',to:'Σε',convert:'Μετατροπή',length:'Μήκος',mass:'Μάζα',volume:'Όγκος',data:'Δεδομένα'},en:{calc:'Calculator',fuel:'Fuel',energy:'Energy',vat:'VAT',units:'Units',how:'How was this calculated?',history:'History',copy:'Copy result',copied:'Copied',clear:'Clear all',confirm:'Delete all calculation history?',confirmYes:'Delete',none:'No calculations yet.',hint:'Enter a calculation to get started.',delete:'Delete',created:'Created by',fuelD:'Distance (km)',fuelC:'Consumption (L/100 km)',fuelP:'Fuel price / L',fuelGo:'Calculate fuel cost',fuelUsed:'Fuel used',costKm:'Cost per km',energyP:'Power (W)',energyH:'Hours / day',energyD:'Days',energyR:'Price / kWh',energyGo:'Calculate electricity cost',energyUsed:'Energy',amount:'Amount',vatRate:'VAT %',addVat:'Add VAT',removeVat:'Remove VAT',vatAmount:'VAT amount',value:'Value',category:'Category',from:'From',to:'To',convert:'Convert',length:'Length',mass:'Mass',volume:'Volume',data:'Data'}};
const t=k=>T[lang][k]??T.en[k]??k;
const fmt=n=>Number.isFinite(Number(n))?new Intl.NumberFormat(lang==='el'?'el-GR':'en-US',{maximumFractionDigits:10}).format(Number(n)):'Error';
const pretty=s=>String(s).replace(/\*/g,'×').replace(/\//g,'÷');
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function tokenize(input){const s=input.replace(/×/g,'*').replace(/÷/g,'/').replace(/,/g,'.').replace(/\s+/g,'');const tokens=[];let i=0;while(i<s.length){const ch=s[i];if(/[0-9.]/.test(ch)){let start=i,dots=0;while(i<s.length&&/[0-9.]/.test(s[i])){if(s[i]==='.')dots++;i++;}if(dots>1)throw Error();const n=Number(s.slice(start,i));if(!Number.isFinite(n))throw Error();let percent=false;if(s[i]==='%'){percent=true;i++;}tokens.push({type:'number',value:n,percent});continue}if('+-*/()'.includes(ch)){tokens.push({type:ch});i++;continue}throw Error()}return tokens}
function evalExpr(input){const tokens=tokenize(input);let pos=0;function primary(){const tok=tokens[pos++];if(!tok)throw Error();if(tok.type==='('){const v=additive();if(!tokens[pos]||tokens[pos].type!==')')throw Error();pos++;return v}if(tok.type==='number')return {value:tok.value,percent:tok.percent};throw Error()}function mult(){let left=primary();while(tokens[pos]&&['*','/'].includes(tokens[pos].type)){const op=tokens[pos++].type;const right=primary();if(op==='*')left={value:left.value*(right.percent?right.value/100:right.value),percent:false};else{const divisor=right.percent?right.value/100:right.value;if(divisor===0)throw Error();left={value:left.value/divisor,percent:false}}}return left}function additive(){let left=mult();while(tokens[pos]&&['+','-'].includes(tokens[pos].type)){const op=tokens[pos++].type;const right=mult();const rv=right.percent?left.value*right.value/100:right.value;left={value:op==='+'?left.value+rv:left.value-rv,percent:false}}return left}const out=additive();if(pos!==tokens.length||!Number.isFinite(out.value))throw Error();return out.value}
function percentExplanation(input,result){const m=String(input).match(/^(-?\d+(?:\.\d+)?)\s*([+-])\s*(\d+(?:\.\d+)?)%$/);if(!m)return null;const base=Number(m[1]),rate=Number(m[3]),part=base*rate/100,total=m[2]==='+'?base+part:base-part;return{formula:pretty(input),steps:[`${fmt(rate)}% ${lang==='el'?'του':'of'} ${fmt(base)} = ${fmt(part)}`,`${fmt(base)} ${m[2]==='+'?'+':'−'} ${fmt(part)} = ${fmt(total)}`],result:fmt(result)}}
function resetHow(){howData=null;$('#howButton').classList.add('hidden')}
function render(){const display=justCalculated?fmt(lastResult):(pretty(expression+current)||'0');$('#expression').textContent=justCalculated?pretty(lastExpression):'';$('#result').textContent=display;$('#clearButton').textContent=current?'C':'AC';$('#howButton').classList.toggle('hidden',!howData)}
function clearAll(){expression='';current='';justCalculated=false;lastExpression='';lastResult=null;resetHow();render()}
function clearCurrent(){resetHow();if(current){current='';render();return}clearAll()}
function backspace(){resetHow();if(justCalculated){clearAll();return}if(current)current=current.slice(0,-1);else if(expression)expression=expression.slice(0,-1);render()}
function digit(v){resetHow();if(justCalculated){expression='';current='';justCalculated=false;lastExpression='';lastResult=null}if(v==='.'&&current.includes('.'))return;if(v==='.'&&!current)current='0.';else if(current==='0'&&v!=='.')current=v;else current+=v;render()}
function operator(op){resetHow();if(justCalculated){expression=String(lastResult);current='';justCalculated=false;lastExpression='';lastResult=null}if(!current&&!expression)return;if(current){expression+=current;current=''}if(/[+\-×÷]$/.test(expression))expression=expression.slice(0,-1)+op;else expression+=op;render()}
function percent(){resetHow();if(!current)return;current=String(Number(current)/100);render()}
function equals(){const full=expression+current;if(!full||/[+\-×÷]$/.test(full))return;try{const value=evalExpr(full);lastExpression=full;lastResult=value;justCalculated=true;howData=percentExplanation(full,value)||{formula:pretty(full),steps:[`${pretty(full)} = ${fmt(value)}`],result:fmt(value)};saveHistory({expression:full,result:value,how:howData});render()}catch{current='Error';render();setTimeout(()=>{if(current==='Error'){current='';render()}},900)}}
function showHow(){if(!howData)return;$('#howTitle').textContent=t('how');$('#howContent').innerHTML=`<div class="how-step"><div class="how-formula">${esc(howData.formula)}</div>${howData.steps.map((s,i)=>`<div class="how-line"><span>${i+1}</span>${esc(s)}</div>`).join('')}<div class="how-result">= ${esc(howData.result)}</div></div>`;$('#howModal').classList.remove('hidden')}
function closeHow(){$('#howModal').classList.add('hidden')}
function historyItems(){try{return JSON.parse(localStorage.getItem('uc-history')||'[]')}catch{return[]}}
function saveHistory(item){const list=historyItems();list.unshift({id:Date.now()+Math.random(),...item});localStorage.setItem('uc-history',JSON.stringify(list.slice(0,100)));renderHistory()}
function renderHistory(){const list=historyItems();$('#historyList').innerHTML=list.length?list.map(x=>`<div class="history-item"><button class="history-main" data-history="${x.id}" type="button"><div class="history-expression">${esc(pretty(x.expression))}</div><div class="history-result">${esc(fmt(x.result))}</div></button><button class="history-delete" data-delete="${x.id}" type="button" aria-label="${esc(t('delete'))}">×</button></div>`).join(''):`<div class="empty">${esc(t('none'))}</div>`}
const units={length:{mm:1,cm:.01,m:1,km:1000,in:.0254,ft:.3048,yd:.9144,mi:1609.344},mass:{mg:.000001,g:.001,kg:1,oz:.028349523125,lb:.45359237},volume:{ml:.001,l:1,tsp:.00492892159,tbsp:.0147867648,cup:.2365882365,gal:3.785411784},data:{B:1,KB:1024,MB:1048576,GB:1073741824,TB:1099511627776}};
const field=(id,label)=>`<label class="tool-field"><span>${esc(label)}</span><input id="${id}" type="number" step="any" inputmode="decimal"></label>`;
function populateUnits(){const cat=$('#unitCategory');if(!cat)return;const keys=Object.keys(units[cat.value]);$('#unitFrom').innerHTML=keys.map(x=>`<option value="${x}">${x}</option>`).join('');$('#unitTo').innerHTML=keys.map(x=>`<option value="${x}">${x}</option>`).join('')}
function bindTools(){const out=$('#toolResult');$('#fuelGo')?.addEventListener('click',()=>{const d=+$('#fuelD').value,c=+$('#fuelC').value,p=+$('#fuelP').value;if([d,c,p].some(x=>!Number.isFinite(x))||d===0)return;const used=d*c/100,cost=used*p;out.innerHTML=`<div><strong>${fmt(cost)} €</strong></div><div>${t('fuelUsed')}: ${fmt(used)} L · ${t('costKm')}: ${fmt(cost/d)} €/km</div>`});$('#energyGo')?.addEventListener('click',()=>{const p=+$('#energyP').value,h=+$('#energyH').value,d=+$('#energyD').value,r=+$('#energyR').value;if([p,h,d,r].some(x=>!Number.isFinite(x)))return;const kwh=p/1000*h*d,cost=kwh*r;out.innerHTML=`<div><strong>${fmt(cost)} €</strong></div><div>${t('energyUsed')}: ${fmt(kwh)} kWh</div>`});const vat=add=>{const a=+$('#amount').value,r=+$('#vatRate').value;if(!Number.isFinite(a)||!Number.isFinite(r))return;const total=add?a*(1+r/100):a/(1+r/100),tax=add?total-a:a-total;out.innerHTML=`<div><strong>${fmt(total)} €</strong></div><div>${t('vatAmount')}: ${fmt(Math.abs(tax))} €</div>`};$('#addVat')?.addEventListener('click',()=>vat(true));$('#removeVat')?.addEventListener('click',()=>vat(false));$('#unitCategory')?.addEventListener('change',populateUnits);$('#convert')?.addEventListener('click',()=>{const v=+$('#value').value,c=$('#unitCategory').value,f=$('#unitFrom').value,to=$('#unitTo').value;if(!Number.isFinite(v))return;out.innerHTML=`<div><strong>${fmt(v*units[c][f]/units[c][to])} ${esc(to)}</strong></div>`})}
function renderTool(){if(mode==='calc'){$('#toolPanel').classList.add('hidden');$('#keypad').classList.remove('hidden');return}$('#keypad').classList.add('hidden');$('#toolPanel').classList.remove('hidden');let html='';if(mode==='fuel')html=`<div class="tool-grid">${field('fuelD',t('fuelD'))}${field('fuelC',t('fuelC'))}${field('fuelP',t('fuelP'))}</div><button class="tool-action" id="fuelGo" type="button">${t('fuelGo')}</button><div id="toolResult" class="tool-result"></div>`;if(mode==='energy')html=`<div class="tool-grid">${field('energyP',t('energyP'))}${field('energyH',t('energyH'))}${field('energyD',t('energyD'))}${field('energyR',t('energyR'))}</div><button class="tool-action" id="energyGo" type="button">${t('energyGo')}</button><div id="toolResult" class="tool-result"></div>`;if(mode==='vat')html=`<div class="tool-grid">${field('amount',t('amount'))}${field('vatRate',t('vatRate'))}</div><div class="tool-grid"><button class="tool-action" id="addVat" type="button">${t('addVat')}</button><button class="tool-action" id="removeVat" type="button">${t('removeVat')}</button></div><div id="toolResult" class="tool-result"></div>`;if(mode==='units')html=`<div class="tool-grid">${field('value',t('value'))}<label class="tool-field"><span>${t('category')}</span><select id="unitCategory"><option value="length">${t('length')}</option><option value="mass">${t('mass')}</option><option value="volume">${t('volume')}</option><option value="data">${t('data')}</option></select></label><label class="tool-field"><span>${t('from')}</span><select id="unitFrom"></select></label><label class="tool-field"><span>${t('to')}</span><select id="unitTo"></select></label></div><button class="tool-action" id="convert" type="button">${t('convert')}</button><div id="toolResult" class="tool-result"></div>`;$('#toolPanel').innerHTML=html;if(mode==='units')populateUnits();bindTools()}
function setMode(next){mode=next;$$('.tab').forEach(b=>b.classList.toggle('active',b.dataset.mode===next));expression='';current='';justCalculated=false;lastExpression='';lastResult=null;resetHow();renderTool();render()}
function applyLanguage(){document.documentElement.lang=lang;$('#langButton').textContent=lang==='el'?'ΕΛ':'EN';$$('.tab').forEach(b=>b.textContent=t(b.dataset.mode));$('#historyButton').textContent=t('history');$('#copyButton').textContent=t('copy');$('#hint').textContent=t('hint');$('#createdBy').textContent=`${t('created')} Leonidas Kampaxis`;$('#historyTitle').textContent=t('history');$('#clearHistory').textContent=t('clear');$('#howTitle').textContent=t('how');renderTool();renderHistory();render()}
function openHistoryConfirm(){$('#historyConfirm').classList.remove('hidden');$('#historyConfirmText').textContent=t('confirm');$('#clearHistory').classList.add('hidden')}
function closeHistoryConfirm(){$('#historyConfirm').classList.add('hidden');$('#clearHistory').classList.remove('hidden')}
$('#keypad').addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;const a=b.dataset.action,v=b.dataset.value;if(a==='clear'){if(current)clearCurrent();else clearAll()}else if(a==='backspace')backspace();else if(a==='equals')equals();else if(v==='%')percent();else if(/[+\-*/]/.test(v||''))operator(v==='*'?'×':v==='/'?'÷':v);else if(v)digit(v)});
$('#howButton').addEventListener('click',showHow);$('#closeHow').addEventListener('click',closeHow);$('#howModal').addEventListener('click',e=>{if(e.target.id==='howModal')closeHow()});$('#historyButton').addEventListener('click',()=>{closeHistoryConfirm();renderHistory();$('#historyPanel').classList.toggle('hidden')});
$('#copyButton').addEventListener('click',async()=>{const value=justCalculated?lastResult:(current||expression);if(value!==''&&navigator.clipboard){await navigator.clipboard.writeText(String(value));$('#copyButton').textContent=t('copied');setTimeout(()=>$('#copyButton').textContent=t('copy'),900)}});$('#langButton').addEventListener('click',()=>{lang=lang==='el'?'en':'el';localStorage.setItem('uc-lang',lang);applyLanguage()});$('#themeButton').addEventListener('click',()=>document.body.classList.toggle('light'));$$('.tab').forEach(b=>b.addEventListener('click',()=>setMode(b.dataset.mode)));
$('#clearHistory').addEventListener('click',openHistoryConfirm);$('#historyConfirmYes').addEventListener('click',()=>{localStorage.removeItem('uc-history');closeHistoryConfirm();renderHistory()});$('#historyList').addEventListener('click',e=>{const del=e.target.closest('[data-delete]'),item=e.target.closest('[data-history]');if(del){localStorage.setItem('uc-history',JSON.stringify(historyItems().filter(x=>String(x.id)!==del.dataset.delete)));renderHistory()}if(item){const x=historyItems().find(x=>String(x.id)===item.dataset.history);if(x){mode='calc';$$('.tab').forEach(b=>b.classList.toggle('active',b.dataset.mode==='calc'));expression='';current=String(x.result);justCalculated=true;lastExpression=x.expression;lastResult=x.result;howData=x.how;renderTool();render()}}});
document.addEventListener('pointerdown',e=>{const confirm=$('#historyConfirm');if(!confirm.classList.contains('hidden')&&!confirm.contains(e.target)&&e.target!==$('#clearHistory'))closeHistoryConfirm()});
window.addEventListener('keydown',e=>{if(/^F\d{1,2}$/.test(e.key)){e.preventDefault();return}const tag=(e.target?.tagName||'').toLowerCase();if(['input','select','textarea'].includes(tag))return;let handled=true;if(/^[0-9]$/.test(e.key)||e.key==='.')digit(e.key);else if(['+','-','*','/'].includes(e.key))operator(e.key==='*'?'×':e.key==='/'?'÷':e.key);else if(e.key==='%')percent();else if(e.key==='Enter'||e.key==='=')equals();else if(e.key==='Backspace'||e.key==='Delete')backspace();else if(e.key==='Escape')clearAll();else handled=false;if(handled)e.preventDefault()});
document.documentElement.lang=lang;$('#version').textContent=`v${VERSION}`;$('#footerVersion').textContent=`v${VERSION}`;applyLanguage();
