const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const VERSION='0.2.7';
let expression='',current='0',result=null,resultExpression='',explanation=null,mode='calc',lang=localStorage.getItem('uc-lang')||'el';
const T={el:{calc:'Υπολογισμός',fuel:'Καύσιμα',energy:'Ενέργεια',vat:'ΦΠΑ',units:'Μονάδες',how:'Πώς;',history:'Ιστορικό',copy:'Αντιγραφή αποτελέσματος',copied:'Αντιγράφηκε',clear:'Διαγραφή όλων',confirm:'Να διαγραφεί όλο το ιστορικό;',confirmYes:'Διαγραφή',cancel:'Ακύρωση',none:'Δεν υπάρχουν υπολογισμοί ακόμα.',hint:'Δοκίμασε 20 + 25% ή άνοιξε ένα εργαλείο.',fuelD:'Απόσταση (km)',fuelC:'Κατανάλωση (L/100 km)',fuelP:'Τιμή καυσίμου / L',fuelGo:'Υπολόγισε κόστος καυσίμων',fuelUsed:'Καύσιμο που χρησιμοποιήθηκε',costKm:'Κόστος ανά km',energyP:'Ισχύς (W)',energyH:'Ώρες / ημέρα',energyD:'Ημέρες',energyR:'Τιμή / kWh',energyGo:'Υπολόγισε κόστος ρεύματος',energyUsed:'Ενέργεια',amount:'Ποσό',vatRate:'ΦΠΑ %',addVat:'Πρόσθεσε ΦΠΑ',removeVat:'Αφαίρεσε ΦΠΑ',vatAmount:'Ποσό ΦΠΑ',value:'Τιμή',category:'Κατηγορία',from:'Από',to:'Σε',convert:'Μετατροπή',normal:'Ο υπολογιστής εφαρμόζει τη μαθηματική σειρά πράξεων.',percent:p=>`${p}% σημαίνει ${p} στα 100.`,of:p=>`${p}% του`,add:'Πρόσθεσέ το',sub:'Αφαίρεσέ το'},en:{calc:'Calc',fuel:'Fuel',energy:'Energy',vat:'VAT',units:'Units',how:'How?',history:'History',copy:'Copy result',copied:'Copied',clear:'Clear all',confirm:'Delete all calculation history?',confirmYes:'Delete',cancel:'Cancel',none:'No calculations yet.',hint:'Try 20 + 25% or open a tool.',fuelD:'Distance (km)',fuelC:'Consumption (L/100 km)',fuelP:'Fuel price / L',fuelGo:'Calculate fuel cost',fuelUsed:'Fuel used',costKm:'Cost per km',energyP:'Power (W)',energyH:'Hours / day',energyD:'Days',energyR:'Price / kWh',energyGo:'Calculate electricity cost',energyUsed:'Energy',amount:'Amount',vatRate:'VAT %',addVat:'Add VAT',removeVat:'Remove VAT',vatAmount:'VAT amount',value:'Value',category:'Category',from:'From',to:'To',convert:'Convert',normal:'The calculator applies normal mathematical order of operations.',percent:p=>`${p}% means ${p} out of every 100.`,of:p=>`${p}% of`,add:'Add it',sub:'Subtract it'}};
const t=k=>T[lang][k]??T.en[k]??k,fmt=n=>Number.isFinite(n)?new Intl.NumberFormat(lang==='el'?'el-GR':'en-US',{maximumFractionDigits:10}).format(Math.abs(n)<1e-12?0:n):'Error',esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const db=new Promise((res,rej)=>{const r=indexedDB.open('ultimate-calculator',1);r.onupgradeneeded=()=>r.result.createObjectStore('history',{keyPath:'id',autoIncrement:true});r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)});
async function allHistory(){const d=await db;return new Promise((res,rej)=>{const r=d.transaction('history').objectStore('history').getAll();r.onsuccess=()=>res(r.result.sort((a,b)=>b.time-a.time));r.onerror=()=>rej(r.error)})}async function addHistory(x){const d=await db;d.transaction('history','readwrite').objectStore('history').add({...x,time:Date.now()})}async function delHistory(id){const d=await db;d.transaction('history','readwrite').objectStore('history').delete(Number(id))}async function clearAllHistory(){const d=await db;await new Promise((res,rej)=>{const r=d.transaction('history','readwrite').objectStore('history').clear();r.onsuccess=res;r.onerror=()=>rej(r.error)});renderHistory()}
function setText(id,v){const e=$(id);if(e)e.textContent=v}function clearLabel(){return current!=='0'&&current!==''?'C':'AC'}
function translate(){document.documentElement.lang=lang;setText('#langButton',lang==='el'?'ΕΛ':'EN');setText('#version','v'+VERSION);setText('#footerVersion','v'+VERSION);setText('#howButton',t('how'));setText('#historyButton',t('history'));setText('#copyButton',t('copy'));setText('#clearHistory',t('clear'));setText('#hint',t('hint'));$$('.tab').forEach(b=>b.textContent=t(b.dataset.mode));setText('#clearButton',clearLabel());setText('#historyConfirmText',t('confirm'));setText('#historyConfirmYes',t('confirmYes'));setText('#historyConfirmCancel',t('cancel'));renderTool();renderHistory();renderDisplay()}function toggleLanguage(){lang=lang==='el'?'en':'el';localStorage.setItem('uc-lang',lang);translate();if(explanation&&!$('#howPanel').classList.contains('hidden'))showHow()}
function evaluate(s){const a=(s.replace(/,/g,'').match(/(?:\d*\.\d+|\d+\.?\d*|[+\-*/%()])/g)||[]).map(x=>['+','-','*','/','%','(',')'].includes(x)?x:Number(x));let i=0;function p(){if(a[i]==='-'){i++;return-p()}if(a[i]==='('){i++;const v=add();if(a[i++]!==')')throw Error();return v}let n=a[i++];if(typeof n!=='number')throw Error();if(a[i]==='%'){i++;n/=100}return n}function m(){let v=p();while(a[i]==='*'||a[i]==='/'){const o=a[i++],r=p();if(o==='/'&&r===0)throw Error();v=o==='*'?v*r:v/r}return v}function add(){let v=m();while(a[i]==='+'||a[i]==='-'){const o=a[i++],r=m();v=o==='+'?v+r:v-r}return v}const v=add();if(i!==a.length)throw Error();return v}
function makeHow(e,v){const m=e.match(/^(-?[\d.]+)\s*([+-])\s*(\d+(?:\.\d+)?)%$/);if(!m)return{summary:t('normal'),steps:[{title:lang==='el'?'Υπολογισμός':'Calculation',formula:e,result:fmt(v)}]};const base=+m[1],p=+m[3],amount=base*p/100;return{summary:t('percent')(p),steps:[{title:t('of')(p),formula:`${fmt(base)} × ${p/100}`,result:fmt(amount)},{title:m[2]==='+'?t('add'):t('sub'),formula:`${fmt(base)} ${m[2]} ${fmt(amount)}`,result:fmt(v)}]}}
function renderDisplay(){const ex=$('#expression'),r=$('#result');if(result!==null&&resultExpression===expression){ex.textContent=resultExpression+' =';r.textContent=fmt(result)}else{ex.textContent=expression||'';r.textContent=current||'0'}setText('#clearButton',clearLabel());$('#howButton').classList.toggle('hidden',!(result!==null&&resultExpression===expression&&explanation))}
function resetEdit(){result=null;resultExpression='';explanation=null;$('#howPanel').classList.add('hidden')}
function inputDigit(v){resetEdit();if(current==='Error')current='0';if(current==='0'&&v!=='.')current=v;else if(v==='.'&&!current.includes('.'))current+='.';else current+=v;expression=expression.replace(/(?:\d*\.?\d+%?)$/,'')+current;renderDisplay()}
function op(v){if(current==='Error')return;resetEdit();if(!expression)expression=current;else if(/[+\-*/]\s*$/.test(expression)&&current==='0')expression=expression.slice(0,-1).trimEnd();expression=expression.trimEnd()+` ${v} `;current='0';renderDisplay()}
function pct(){if(current==='0'||current==='Error')return;resetEdit();if(!current.endsWith('%')){current+='%';expression=expression.replace(/(?:\d*\.?\d+%?)$/,'')+current}renderDisplay()}
function backspace(){resetEdit();if(current!=='0'&&current!==''){current=current.slice(0,-1)||'0';expression=expression.replace(/(?:\d*\.?\d+%?)$/,'')+current;if(current==='0')expression=expression.replace(/0$/,'')}else if(expression){expression=expression.trimEnd();if(/[+\-*/]$/.test(expression))expression=expression.slice(0,-1).trimEnd();else expression=expression.replace(/(?:\d*\.?\d+%?)$/,'');const m=expression.match(/(?:\d*\.?\d+%?)$/);current=m?m[0]:'0'}renderDisplay()}
function clearCurrent(){resetEdit();if(current!=='0'&&current!==''){current='0';expression=expression.replace(/(?:\d*\.?\d+%?)$/,'');renderDisplay();return}clearAll()}function clearAll(){expression='';current='0';result=null;resultExpression='';explanation=null;$('#howPanel').classList.add('hidden');renderDisplay()}
async function calculate(){const full=expression.trim();if(!full||/[+\-*/]$/.test(full))return;try{const v=evaluate(full);result=v;resultExpression=full;current=String(v);explanation=makeHow(full,v);await addHistory({expression:full,result:fmt(v),explanation});renderDisplay();renderHistory()}catch{current='Error';result=null;renderDisplay()}}
function showHow(){if(!explanation)return;$('#howContent').innerHTML=`<p class="how-summary">${esc(explanation.summary)}</p>`+explanation.steps.map(s=>`<div class="how-step"><div class="how-title">${esc(s.title)}</div><div class="how-formula">${esc(s.formula)}</div><div class="how-result">${esc(s.result)}</div></div>`).join('');$('#howPanel').classList.remove('hidden')}
async function renderHistory(){const items=await allHistory(),list=$('#historyList');if(!list)return;list.innerHTML=items.length?items.map(x=>`<div class="history-item"><button class="history-main" data-id="${x.id}"><div class="history-expression">${esc(x.expression)}</div><div class="history-result">${esc(x.result)}</div></button><button class="history-delete" data-del="${x.id}" aria-label="Delete">×</button></div>`).join(''):`<div class="empty">${t('none')}</div>`;$$('[data-id]').forEach(b=>b.onclick=()=>{const x=items.find(i=>String(i.id)===b.dataset.id);expression=x.expression;current=x.result;result=Number(String(x.result).replace(/,/g,''));resultExpression=x.expression;explanation=x.explanation;mode='calc';setMode();renderDisplay()});$$('[data-del]').forEach(b=>b.onclick=async()=>{await delHistory(b.dataset.del);renderHistory()})}
function showHistoryConfirm(){const e=$('#historyConfirm');e.classList.remove('hidden');$('#clearHistory').classList.add('hidden')}function hideHistoryConfirm(){const e=$('#historyConfirm');e.classList.add('hidden');$('#clearHistory').classList.remove('hidden')}
const unitDefs={length:{m:1,km:1000,cm:.01,mm:.001,ft:.3048,mi:1609.344},mass:{kg:1,g:.001,lb:.45359237,oz:.0283495231},volume:{l:1,ml:.001,gal:3.785411784},data:{B:1,KB:1000,MB:1e6,GB:1e9,TB:1e12}};
function toolResult(html){const e=$('#toolResult');if(e){e.innerHTML=html;e.classList.remove('hidden')}}
function renderTool(){const p=$('#toolPanel');if(!p)return;if(mode==='calc'){p.classList.add('hidden');p.innerHTML='';$('#keypad').classList.remove('hidden');$('#calculatorDisplay').classList.remove('hidden');return}$('#keypad').classList.add('hidden');$('#calculatorDisplay').classList.add('hidden');p.classList.remove('hidden');if(mode==='fuel')p.innerHTML=`<div class="tool-grid"><label class="tool-field"><span>${t('fuelD')}</span><input id="fuelD" type="number" inputmode="decimal"></label><label class="tool-field"><span>${t('fuelC')}</span><input id="fuelC" type="number" inputmode="decimal"></label><label class="tool-field"><span>${t('fuelP')}</span><input id="fuelP" type="number" inputmode="decimal"></label></div><button class="tool-action" id="fuelGo">${t('fuelGo')}</button><div id="toolResult" class="tool-result hidden"></div>`;else if(mode==='energy')p.innerHTML=`<div class="tool-grid"><label class="tool-field"><span>${t('energyP')}</span><input id="energyP" type="number" inputmode="decimal"></label><label class="tool-field"><span>${t('energyH')}</span><input id="energyH" type="number" inputmode="decimal"></label><label class="tool-field"><span>${t('energyD')}</span><input id="energyD" type="number" inputmode="decimal" value="30"></label><label class="tool-field"><span>${t('energyR')}</span><input id="energyR" type="number" inputmode="decimal"></label></div><button class="tool-action" id="energyGo">${t('energyGo')}</button><div id="toolResult" class="tool-result hidden"></div>`;else if(mode==='vat')p.innerHTML=`<label class="tool-field"><span>${t('amount')}</span><input id="vatAmount" type="number" inputmode="decimal"></label><label class="tool-field"><span>${t('vatRate')}</span><input id="vatRate" type="number" inputmode="decimal" value="24"></label><div class="bottom-actions"><button class="tool-action" id="addVat">${t('addVat')}</button><button class="tool-action" id="removeVat">${t('removeVat')}</button></div><div id="toolResult" class="tool-result hidden"></div>`;else if(mode==='units')p.innerHTML=`<div class="tool-grid"><label class="tool-field"><span>${t('category')}</span><select id="unitCat"><option value="length">${lang==='el'?'Μήκος':'Length'}</option><option value="mass">${lang==='el'?'Μάζα':'Mass'}</option><option value="volume">${lang==='el'?'Όγκος':'Volume'}</option><option value="data">${lang==='el'?'Δεδομένα':'Data'}</option></select></label><label class="tool-field"><span>${t('value')}</span><input id="unitVal" type="number" inputmode="decimal"></label><label class="tool-field"><span>${t('from')}</span><select id="unitFrom"></select></label><label class="tool-field"><span>${t('to')}</span><select id="unitTo"></select></label></div><button class="tool-action" id="unitGo">${t('convert')}</button><div id="toolResult" class="tool-result hidden"></div>`;bindTools()}
function bindTools(){if($('#fuelGo'))$('#fuelGo').onclick=()=>{const d=+$('#fuelD').value,c=+$('#fuelC').value,p=+$('#fuelP').value;if(!(d>0&&c>0&&p>=0))return toolResult('Enter valid values.');const u=d*c/100,cost=u*p;toolResult(`<strong>${fmt(cost)}</strong><br>${t('fuelUsed')}: ${fmt(u)} L<br>${t('costKm')}: ${fmt(cost/d)}`)};if($('#energyGo'))$('#energyGo').onclick=()=>{const p=+$('#energyP').value,h=+$('#energyH').value,d=+$('#energyD').value,r=+$('#energyR').value;if(!(p>0&&h>0&&d>0&&r>=0))return toolResult('Enter valid values.');const k=p/1000*h*d;toolResult(`<strong>${fmt(k*r)}</strong><br>${t('energyUsed')}: ${fmt(k)} kWh`)};if($('#addVat'))$('#addVat').onclick=()=>vat(true);if($('#removeVat'))$('#removeVat').onclick=()=>vat(false);if($('#unitCat')){const fill=()=>{const o=unitDefs[$('#unitCat').value];['unitFrom','unitTo'].forEach(id=>$('#'+id).innerHTML=Object.keys(o).map(k=>`<option value="${k}">${k}</option>`).join(''))};$('#unitCat').onchange=fill;fill();$('#unitGo').onclick=()=>{const v=+$('#unitVal').value,f=$('#unitFrom').value,to=$('#unitTo').value;if(!Number.isFinite(v))return toolResult('Enter a valid value.');const out=v*unitDefs[$('#unitCat').value][f]/unitDefs[$('#unitCat').value][to];toolResult(`<strong>${fmt(out)} ${to}</strong>`)}}}
function vat(add){const a=+$('#vatAmount').value,r=+$('#vatRate').value;if(!(a>=0&&r>=0))return toolResult('Enter valid values.');const total=add?a*(1+r/100):a/(1+r/100),vat=add?a*r/100:a-total;toolResult(`<strong>${fmt(total)}</strong><br>${t('vatAmount')}: ${fmt(vat)}`)}
function setMode(){mode=mode||'calc';$$('.tab').forEach(b=>b.classList.toggle('active',b.dataset.mode===mode));renderTool()}
$$('.key').forEach(b=>b.addEventListener('click',()=>{const a=b.dataset.action,v=b.dataset.value;if(a==='clear'){if(clearLabel()==='C')clearCurrent();else clearAll()}else if(a==='backspace')backspace();else if(a==='equals')calculate();else if(v==='%')pct();else if(v&&'+-*/'.includes(v))op(v);else if(v)inputDigit(v)}));
$('#howButton').onclick=showHow;$('#closeHow').onclick=()=>$('#howPanel').classList.add('hidden');$('#historyButton').onclick=()=>{$('#historyPanel').classList.toggle('hidden');renderHistory()};$('#clearHistory').onclick=showHistoryConfirm;$('#historyConfirmYes').onclick=async()=>{await clearAllHistory();hideHistoryConfirm()};$('#historyConfirmCancel').onclick=hideHistoryConfirm;$('#copyButton').onclick=async()=>{if(result===null)return;try{await navigator.clipboard.writeText(String(result));setText('#copyButton',t('copied'));setTimeout(()=>setText('#copyButton',t('copy')),1200)}catch{}};$$('.tab').forEach(b=>b.onclick=()=>{mode=b.dataset.mode;setMode()});$('#langButton').onclick=toggleLanguage;$('#themeButton').onclick=()=>document.body.classList.toggle('light');
document.addEventListener('keydown',e=>{if(e.target.matches('input,select'))return;if(e.key==='Enter'||e.key==='='){e.preventDefault();calculate()}else if(e.key==='Backspace'){e.preventDefault();backspace()}else if(e.key==='Escape'){e.preventDefault();clearAll()}else if(/[0-9.]/.test(e.key)){e.preventDefault();inputDigit(e.key)}else if(e.key==='%'){e.preventDefault();pct()}else if('+-*/'.includes(e.key)){e.preventDefault();op(e.key)}});
document.documentElement.lang=lang;translate();renderDisplay();renderHistory();
