const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const VERSION='0.2.6';
let expression='', current='0', result=null, resultExpression='', explanation=null, mode='calc', lang=localStorage.getItem('uc-lang')||'el';
const T={el:{calc:'Υπολογισμός',fuel:'Καύσιμα',energy:'Ενέργεια',vat:'ΦΠΑ',units:'Μονάδες',how:'Πώς;',history:'Ιστορικό',copy:'Αντιγραφή αποτελέσματος',copied:'Αντιγράφηκε',clear:'Διαγραφή όλων',none:'Δεν υπάρχουν υπολογισμοί ακόμα.',confirm:'Να διαγραφεί όλο το ιστορικό;',hint:'Δοκίμασε 20 + 25% ή άνοιξε ένα εργαλείο.',fuelD:'Απόσταση (km)',fuelC:'Κατανάλωση (L/100 km)',fuelP:'Τιμή καυσίμου / L',fuelGo:'Υπολόγισε κόστος καυσίμων',fuelUsed:'Καύσιμο που χρησιμοποιήθηκε',costKm:'Κόστος ανά km',energyP:'Ισχύς (W)',energyH:'Ώρες / ημέρα',energyD:'Ημέρες',energyR:'Τιμή / kWh',energyGo:'Υπολόγισε κόστος ρεύματος',energyUsed:'Ενέργεια',amount:'Ποσό',vatRate:'ΦΠΑ %',addVat:'Πρόσθεσε ΦΠΑ',removeVat:'Αφαίρεσε ΦΠΑ',vatAmount:'Ποσό ΦΠΑ',value:'Τιμή',category:'Κατηγορία',from:'Από',to:'Σε',convert:'Μετατροπή',normal:'Ο υπολογιστής εφαρμόζει τη μαθηματική σειρά πράξεων.',percent:p=>`${p}% σημαίνει ${p} στα 100.`,of:p=>`${p}% του`,add:'Πρόσθεσέ το',sub:'Αφαίρεσέ το'},en:{calc:'Calc',fuel:'Fuel',energy:'Energy',vat:'VAT',units:'Units',how:'How?',history:'History',copy:'Copy result',copied:'Copied',clear:'Clear all',none:'No calculations yet.',confirm:'Delete all calculation history?',hint:'Try 20 + 25% or open a tool.',fuelD:'Distance (km)',fuelC:'Consumption (L/100 km)',fuelP:'Fuel price / L',fuelGo:'Calculate fuel cost',fuelUsed:'Fuel used',costKm:'Cost per km',energyP:'Power (W)',energyH:'Hours / day',energyD:'Days',energyR:'Price / kWh',energyGo:'Calculate electricity cost',energyUsed:'Energy',amount:'Amount',vatRate:'VAT %',addVat:'Add VAT',removeVat:'Remove VAT',vatAmount:'VAT amount',value:'Value',category:'Category',from:'From',to:'To',convert:'Convert',normal:'The calculator applies normal mathematical order of operations.',percent:p=>`${p}% means ${p} out of every 100.`,of:p=>`${p}% of`,add:'Add it',sub:'Subtract it'}};
const t=k=>T[lang][k]??T.en[k]??k, fmt=n=>Number.isFinite(n)?new Intl.NumberFormat(lang==='el'?'el-GR':'en-US',{maximumFractionDigits:10}).format(Math.abs(n)<1e-12?0:n):'Error', esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function save(){localStorage.setItem('uc-lang',lang)}
const db=new Promise((res,rej)=>{let r=indexedDB.open('ultimate-calculator',1);r.onupgradeneeded=()=>r.result.createObjectStore('history',{keyPath:'id',autoIncrement:true});r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)});
async function allHistory(){let d=await db;return new Promise((res,rej)=>{let r=d.transaction('history').objectStore('history').getAll();r.onsuccess=()=>res(r.result.sort((a,b)=>b.time-a.time));r.onerror=()=>rej(r.error)})}
async function addHistory(x){let d=await db;d.transaction('history','readwrite').objectStore('history').add({...x,time:Date.now()})}
async function delHistory(id){let d=await db;d.transaction('history','readwrite').objectStore('history').delete(Number(id))}
async function clearHistory(){if(!confirm(t('confirm')))return;let d=await db;d.transaction('history','readwrite').objectStore('history').clear();renderHistory()}
function setText(id,v){let e=$(id);if(e)e.textContent=v}
function translate(){document.documentElement.lang=lang;setText('#langButton',lang==='el'?'ΕΛ':'EN');setText('#version','v'+VERSION);setText('#footerVersion','v'+VERSION);setText('#howButton',t('how'));setText('#historyButton',t('history'));setText('#copyButton',t('copy'));setText('#clearHistory',t('clear'));setText('#hint',t('hint'));$$('.tab').forEach(b=>b.textContent=t(b.dataset.mode));setText('#clearButton',clearLabel())}
function toggleLanguage(){lang=lang==='el'?'en':'el';save();translate();renderTool();renderHistory();renderDisplay();if(explanation&&!$('#howPanel').classList.contains('hidden'))showHow()}
function clearLabel(){return expression||result!==null?'C':'AC'}
function evaluate(s){let a=(s.replace(/,/g,'').match(/(?:\d*\.\d+|\d+\.?\d*|[+\-*/%()])/g)||[]).map(x=>['+','-','*','/','%','(',')'].includes(x)?x:Number(x)),i=0;function p(){if(a[i]==='-'){i++;return-p()}if(a[i]==='('){i++;let v=add();if(a[i++]!==')')throw Error();return v}let n=a[i++];if(typeof n!=='number')throw Error();if(a[i]==='%'){i++;n/=100}return n}function m(){let v=p();while(a[i]==='*'||a[i]==='/'){let o=a[i++],r=p();if(o==='/'&&r===0)throw Error();v=o==='*'?v*r:v/r}return v}function add(){let v=m();while(a[i]==='+'||a[i]==='-'){let o=a[i++],r=m();v=o==='+'?v+r:v-r}return v}let v=add();if(i!==a.length)throw Error();return v}
function makeHow(e,v){let m=e.match(/^(-?[\d.]+)\s*([+-])\s*(\d+(?:\.\d+)?)%$/);if(!m)return{summary:t('normal'),steps:[{title:e,formula:e,result:fmt(v)}]};let base=+m[1],p=+m[3],amount=base*p/100;return{summary:t('percent')(p),steps:[{title:t('of')(p),formula:`${fmt(base)} × ${p/100}`,result:fmt(amount)},{title:m[2]==='+'?t('add'):t('sub'),formula:`${fmt(base)} ${m[2]} ${fmt(amount)}`,result:fmt(v)}]}}
function renderDisplay(){let ex=$('#expression'),r=$('#result');if(result!==null&&resultExpression===expression){ex.textContent=resultExpression+' =';r.textContent=fmt(result)}else{let pending=expression.match(/^(.*?)([+\-*/])$/);ex.textContent=pending?pending[1]+' '+pending[2]:'';r.textContent=current||'0'}setText('#clearButton',clearLabel());$('#howButton').classList.toggle('hidden',!(result!==null&&resultExpression===expression&&explanation))}
function resetEdit(){result=null;resultExpression='';explanation=null;$('#howPanel').classList.add('hidden')}
function inputDigit(v){resetEdit();if(current==='Error')current='0';if(current==='0'&&v!=='.')current=v;else if(v==='.'&&!current.includes('.'))current+='.';else current+=v;expression=expression.replace(/(?:\d*\.?\d+%?)$/,'')+current;renderDisplay()}
function op(v){if(current==='Error')return;resetEdit();if(!expression)expression=current;if(/[+\-*/]$/.test(expression))expression=expression.slice(0,-1)+v;else expression+=v;current='0';renderDisplay()}
function pct(){if(current==='0'||current==='Error')return;resetEdit();if(!current.endsWith('%')){current+='%';expression=expression.replace(/(?:\d*\.?\d+%?)$/,'')+current}renderDisplay()}
function backspace(){resetEdit();if(!expression){current='0'}else{expression=expression.slice(0,-1);let m=expression.match(/(?:\d*\.?\d+%?)$/);current=m?m[0]:'0'}renderDisplay()}
function clearCurrent(){if(!expression){current='0';result=null;renderDisplay();return}resetEdit();if(/[+\-*/]$/.test(expression)){expression=expression.slice(0,-1);let m=expression.match(/(?:\d*\.?\d+%?)$/);current=m?m[0]:'0'}else{expression=expression.replace(/(?:\d*\.?\d+%?)$/,'');current='0'}renderDisplay()}
function clearAll(){expression='';current='0';result=null;resultExpression='';explanation=null;$('#howPanel').classList.add('hidden');renderDisplay()}
async function calculate(){if(!expression||/[+\-*/]$/.test(expression))return;try{let v=evaluate(expression);result=v;resultExpression=expression;current=fmt(v);explanation=makeHow(expression,v);await addHistory({expression,result:fmt(v),explanation});renderDisplay();renderHistory()}catch{current='Error';renderDisplay()}}
function showHow(){if(!explanation)return;$('#howContent').innerHTML=`<p class="how-summary">${esc(explanation.summary)}</p>`+explanation.steps.map(s=>`<div class="how-step"><div class="how-title">${esc(s.title)}</div><div class="how-formula">${esc(s.formula)}</div><div class="how-result">${esc(s.result)}</div></div>`).join('');$('#howPanel').classList.remove('hidden')}
async function renderHistory(){let items=await allHistory(),list=$('#historyList');if(!list)return;list.innerHTML=items.length?items.map(x=>`<div class="history-item"><button class="history-main" data-id="${x.id}"><div class="history-expression">${esc(x.expression)}</div><div class="history-result">${esc(x.result)}</div></button><button class="history-delete" data-del="${x.id}">×</button></div>`).join(''):`<div class="empty">${t('none')}</div>`;$$('[data-id]').forEach(b=>b.onclick=()=>{let x=items.find(i=>String(i.id)===b.dataset.id);expression=x.expression;current=x.result;result=Number(String(x.result).replace(/,/g,''));resultExpression=x.expression;explanation=x.explanation;mode='calc';setMode();renderDisplay()});$$('[data-del]').forEach(b=>b.onclick=async()=>{await delHistory(b.dataset.del);renderHistory()})}
const unitDefs={length:{m:1,km:1000,cm:.01,mm:.001,ft:.3048,mi:1609.344},mass:{kg:1,g:.001,lb:.45359237,oz:.0283495231},volume:{l:1,ml:.001,gal:3.785411784}};
function toolResult(html){let e=$('#toolResult');if(e){e.innerHTML=html;e.classList.remove('hidden')}}
function renderTool(){let p=$('#toolPanel');if(!p)return;if(mode==='fuel')p.innerHTML=`<div class="tool-grid"><label class="tool-field">${t('fuelD')}<input id="fuelD" type="number" inputmode="decimal"></label><label class="tool-field">${t('fuelC')}<input id="fuelC" type="number" inputmode="decimal"></label><label class="tool-field">${t('fuelP')}<input id="fuelP" type="number" inputmode="decimal"></label></div><button class="tool-action" id="fuelGo">${t('fuelGo')}</button><div id="toolResult" class="tool-result hidden"></div>`;else if(mode==='energy')p.innerHTML=`<div class="tool-grid"><label class="tool-field">${t('energyP')}<input id="energyP" type="number" inputmode="decimal"></label><label class="tool-field">${t('energyH')}<input id="energyH" type="number" inputmode="decimal"></label><label class="tool-field">${t('energyD')}<input id="energyD" type="number" inputmode="decimal" value="30"></label><label class="tool-field">${t('energyR')}<input id="energyR" type="number" inputmode="decimal"></label></div><button class="tool-action" id="energyGo">${t('energyGo')}</button><div id="toolResult" class="tool-result hidden"></div>`;else if(mode==='vat')p.innerHTML=`<label class="tool-field">${t('amount')}<input id="vatAmount" type="number" inputmode="decimal"></label><label class="tool-field">${t('vatRate')}<input id="vatRate" type="number" inputmode="decimal" value="24"></label><div class="bottom-actions"><button class="tool-action" id="addVat">${t('addVat')}</button><button class="tool-action" id="removeVat">${t('removeVat')}</button></div><div id="toolResult" class="tool-result hidden"></div>`;else if(mode==='units')p.innerHTML=`<div class="tool-grid"><label class="tool-field">${t('category')}<select id="unitCat"><option value="length">${lang==='el'?'Μήκος':'Length'}</option><option value="mass">${lang==='el'?'Μάζα':'Mass'}</option><option value="volume">${lang==='el'?'Όγκος':'Volume'}</option></select></label><label class="tool-field">${t('value')}<input id="unitVal" type="number" inputmode="decimal"></label><label class="tool-field">${t('from')}<select id="unitFrom"></select></label><label class="tool-field">${t('to')}<select id="unitTo"></select></label></div><button class="tool-action" id="unitGo">${t('convert')}</button><div id="toolResult" class="tool-result hidden"></div>`;else p.innerHTML='';bindTools()}
function bindTools(){if($('#fuelGo'))$('#fuelGo').onclick=()=>{let d=+$('#fuelD').value,c=+$('#fuelC').value,p=+$('#fuelP').value,u=d*c/100,cost=u*p;toolResult(`<strong>${fmt(cost)}</strong><br>${t('fuelUsed')}: ${fmt(u)} L<br>${t('costKm')}: ${fmt(cost/d)}`)};if($('#energyGo'))$('#energyGo').onclick=()=>{let p=+$('#energyP').value,h=+$('#energyH').value,d=+$('#energyD').value,r=+$('#energyR').value,k=p/1000*h*d;toolResult(`<strong>${fmt(k*r)}</strong><br>${t('energyUsed')}: ${fmt(k)} kWh`)};if($('#addVat'))$('#addVat').onclick=()=>vat(true);if($('#removeVat'))$('#removeVat').onclick=()=>vat(false);if($('#unitCat')){let fill=()=>{let o=unitDefs[$('#unitCat').value];['unitFrom','unitTo'].forEach(id=>$('#'+id).innerHTML=Object.keys(o).map(k=>`<option value="${k}">${k}</option>`).join(''))};$('#unitCat').onchange=fill;fill();$('#unitGo').onclick=()=>{let o=unitDefs[$('#unitCat').value],v=+$('#unitVal').value,a=$('#unitFrom').value,b=$('#unitTo').value;toolResult(`<strong>${fmt(v*o[a]/o[b])}</strong> ${b}`)}}}
function vat(add){let a=+$('#vatAmount').value,r=+$('#vatRate').value;if(!Number.isFinite(a)||!Number.isFinite(r))return;let total=add?a*(1+r/100):a/(1+r/100),tax=add?total-a:a-total;toolResult(`<strong>${fmt(total)}</strong><br>${t('vatAmount')}: ${fmt(tax)}`)}
function setMode(){let calc=mode==='calc';$('#calculatorDisplay').classList.toggle('hidden',!calc);$('#keypad').classList.toggle('hidden',!calc);$('#toolPanel').classList.toggle('hidden',calc);$$('.tab').forEach(b=>b.classList.toggle('active',b.dataset.mode===mode));if(!calc)$('#howPanel').classList.add('hidden');renderTool()}
function copy(){if(result===null)return;navigator.clipboard?.writeText(fmt(result));let b=$('#copyButton');b.textContent=t('copied');setTimeout(()=>b.textContent=t('copy'),1000)}
$$('.key').forEach(b=>b.onclick=()=>{let a=b.dataset.action,v=b.dataset.value;if(a==='equals')calculate();else if(a==='backspace')backspace();else if(a==='clear')clearCurrent();else if(v==='%')pct();else if(['+','-','*','/'].includes(v))op(v);else if(v)inputDigit(v)});$$('.tab').forEach(b=>b.onclick=()=>{mode=b.dataset.mode;setMode()});$('#howButton').onclick=showHow;$('#closeHow').onclick=()=>$('#howPanel').classList.add('hidden');$('#historyButton').onclick=()=>$('#historyPanel').classList.toggle('hidden');$('#clearHistory').onclick=clearHistory;$('#copyButton').onclick=copy;$('#langButton').onclick=toggleLanguage;$('#themeButton').onclick=()=>document.body.classList.toggle('light');window.addEventListener('keydown',e=>{if(mode!=='calc')return;if(/\d/.test(e.key)||e.key==='.')inputDigit(e.key);else if(['+','-','*','/'].includes(e.key))op(e.key);else if(e.key==='%')pct();else if(e.key==='Backspace')backspace();else if(e.key==='Escape')clearCurrent();else if(e.key==='Enter'||e.key==='=')calculate()});
translate();renderDisplay();renderHistory();setMode();
