const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const VERSION='0.2.1';let expression='',lastResult=null,lastExplanation=null,currentMode='calc',authUser=null,authMode='login';
const fmt=v=>Number.isFinite(v)?new Intl.NumberFormat(undefined,{maximumFractionDigits:10}).format(Math.abs(v)<1e-12?0:v):'Error';const raw=v=>String(Number(v.toPrecision(12)));const esc=v=>String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const dbPromise=new Promise((resolve,reject)=>{const r=indexedDB.open('ultimate-calculator',1);r.onupgradeneeded=()=>r.result.createObjectStore('history',{keyPath:'id',autoIncrement:true});r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)});
async function localItems(){try{const db=await dbPromise,s=db.transaction('history').objectStore('history');return await new Promise((ok,no)=>{const r=s.getAll();r.onsuccess=()=>ok(r.result.sort((a,b)=>b.createdAt-a.createdAt));r.onerror=()=>no(r.error)})}catch{return[]}}
async function localAdd(x){try{const db=await dbPromise;db.transaction('history','readwrite').objectStore('history').add({...x,createdAt:Date.now()})}catch{}}
async function localDelete(id){const db=await dbPromise;db.transaction('history','readwrite').objectStore('history').delete(Number(id))}async function localClear(){const db=await dbPromise;db.transaction('history','readwrite').objectStore('history').clear()}
async function api(path,opts={}){const r=await fetch(path,{credentials:'same-origin',headers:{'Content-Type':'application/json',...(opts.headers||{})},...opts});let d={};try{d=await r.json()}catch{}if(!r.ok)throw Error(d.error||`Request failed (${r.status})`);return d}
async function checkAuth(){try{const d=await api('/api/me');authUser=d.user||null}catch{authUser=null}updateAccountButton()}
function updateAccountButton(){$('#accountButton').textContent=authUser?`${authUser.username} · Sign out`:'Sign in'}
function parseExplanation(v){try{return v?JSON.parse(v):null}catch{return null}}
async function historyItems(){if(authUser){try{const d=await api('/api/history');return d.items.map(i=>({...i,id:i.id,createdAt:i.created_at,explanation:parseExplanation(i.label)}))}catch{}}return localItems()}
async function saveHistory(x){await localAdd(x);if(authUser){try{await api('/api/history',{method:'POST',body:JSON.stringify({expression:x.expression,result:x.result,label:JSON.stringify(x.explanation||null)})})}catch{}}await refreshHistory()}
async function removeHistory(id){if(authUser){try{await api(`/api/history/${id}`,{method:'DELETE'})}catch{}}else await localDelete(id);await refreshHistory()}
async function wipeHistory(){if(authUser){try{await api('/api/history',{method:'DELETE'})}catch{}}await localClear();await refreshHistory()}
async function syncLocalToAccount(){if(!authUser)return;const items=await localItems();for(const x of items){try{await api('/api/history',{method:'POST',body:JSON.stringify({expression:x.expression,result:x.result,label:JSON.stringify(x.explanation||null)})})}catch{}}await localClear()}
function tokenize(s){s=s.replace(/[€$£¥₹]/g,'').replace(/,/g,'');const a=[];let i=0;while(i<s.length){const c=s[i];if(/\s/.test(c)){i++;continue}if(/[0-9.]/.test(c)){let j=i,d=0;while(j<s.length&&/[0-9.]/.test(s[j])){if(s[j]==='.')d++;if(d>1)throw Error();j++}const n=Number(s.slice(i,j));if(!Number.isFinite(n))throw Error();a.push({t:'n',v:n});i=j;continue}if('+-*/()'.includes(c)){a.push({t:c});i++;continue}if(c==='%'){a.push({t:'%'});i++;continue}throw Error()}return a}
function evaluate(s){const t=tokenize(s),p={i:0};function pri(){const x=t[p.i];if(!x)throw Error();if(x.t==='n'){p.i++;let n={v:x.v,p:false};if(t[p.i]?.t==='%'){p.i++;n={v:x.v/100,p:true}}return n}if(x.t==='('){p.i++;const n=add();if(t[p.i]?.t!==')')throw Error();p.i++;if(t[p.i]?.t==='%'){p.i++;return{v:n.v/100,p:true}}return n}if(x.t==='-'){p.i++;const n=pri();return{v:-n.v,p:n.p}}throw Error()}function mul(){let l=pri();while(t[p.i]&&['*','/'].includes(t[p.i].t)){const o=t[p.i++].t,r=pri();if(o==='/'&&r.v===0)throw Error();l={v:o==='*'?l.v*r.v:l.v/r.v,p:false}}return l}function add(){let l=mul();while(t[p.i]&&['+','-'].includes(t[p.i].t)){const o=t[p.i++].t,r=mul(),n=r.p?l.v*r.v:r.v;l={v:o==='+'?l.v+n:l.v-n,p:false}}return l}const r=add();if(p.i!==t.length)throw Error();return r.v}
function step(title,formula,result){return `<div class="how-step"><div class="how-title">${esc(title)}</div><div class="how-formula">${esc(formula)}</div><div class="how-result">${esc(result)}</div></div>`}
function explainExpression(e,v){const s=e.replace(/\s+/g,''),m=s.match(/^(-?[\d.,]+)([+\-])([\d.,]+)%$/);if(m){const a=Number(m[1].replace(/,/g,'')),p=Number(m[3].replace(/,/g,'')),c=a*p/100;return{summary:`${p}% means ${p} out of every 100.`,steps:[step(`${p}% of ${fmt(a)}`,`${fmt(a)} × ${p} ÷ 100`,fmt(c)),step(m[2]==='+'?'Add it':'Subtract it',`${fmt(a)} ${m[2]} ${fmt(c)}`,fmt(v))]}}const q=s.match(/^(-?[\d.]+)([+\-*/])(-?[\d.]+)$/);if(q){const a=Number(q[1]),o=q[2],b=Number(q[3]);return{summary:'The calculator applies the operation between the two numbers.',steps:[step('Calculation',`${fmt(a)} ${o==='*'?'×':o==='/'?'÷':o} ${fmt(b)}`,fmt(v))]}}return{summary:'The result follows normal mathematical order of operations.',steps:[step('Result',e,fmt(v))]}}
function showHow(x=lastExplanation){if(!x)return;$('#howContent').innerHTML=`<p class="how-summary">${esc(x.summary)}</p>${x.steps.join('')}`;$('#howPanel').classList.remove('hidden')}
function invalidateExplanation(){lastExplanation=null;$('#howButton').classList.add('hidden');$('#howPanel').classList.add('hidden')}
function display(v=null){$('#expression').textContent=expression;$('#result').textContent=v===null?(expression?'…':'0'):fmt(v);$('#howButton').classList.toggle('hidden',v===null||!lastExplanation)}
async function calculate(){if(!expression.trim())return;try{const v=evaluate(expression);lastResult=v;lastExplanation=explainExpression(expression,v);display(v);await saveHistory({expression,result:fmt(v),explanation:lastExplanation})}catch{$('#result').textContent='Error';lastResult=null;invalidateExplanation()}}
function append(v){if(v==='.'&&/(^|[+\-*/(])\s*\d*\.\d*$/.test(expression))return;if(v==='%'&&!/[0-9)]$/.test(expression))return;if('+-*/'.includes(v)){if(!expression&&v!=='-')return;if(/[+\-*/]$/.test(expression))expression=expression.slice(0,-1)+v}expression+=v;invalidateExplanation();display()}
function clearAll(){expression='';lastResult=null;invalidateExplanation();display(0)}function back(){expression=expression.slice(0,-1);lastResult=null;invalidateExplanation();display()}
const units={length:{m:1,km:1000,mi:1609.344,ft:.3048,in:.0254,yd:.9144},weight:{kg:1,g:.001,lb:.45359237,oz:.028349523125},volume:{L:1,mL:.001,gal:3.785411784,qt:.946352946,cup:.2365882365},speed:{'km/h':1,mph:1.609344,'m/s':3.6,knot:1.852},temperature:{C:1,F:1,K:1}};const field=(l,id,v)=>`<div class="tool-field"><label>${l}</label><input id="${id}" type="number" value="${v}"></div>`;
function renderTool(m){const p=$('#toolPanel');p.classList.toggle('hidden',m==='calc');if(m==='calc'){p.innerHTML='';return}if(m==='fuel')p.innerHTML=`<div class="tool-grid">${field('Distance (km)','fuelDistance',100)}${field('Consumption (L/100 km)','fuelConsumption',7)}${field('Fuel price / L','fuelPrice',1.8)}</div><div id="toolOutput" class="tool-result">Enter values and calculate.</div><button class="tool-action" data-tool-action="fuel">Calculate fuel cost</button>`;if(m==='energy')p.innerHTML=`<div class="tool-grid">${field('Power (W)','energyPower',100)}${field('Hours / day','energyHours',8)}${field('Days','energyDays',30)}${field('Price / kWh','energyRate',.2)}</div><div id="toolOutput" class="tool-result">Enter values and calculate.</div><button class="tool-action" data-tool-action="energy">Calculate electricity cost</button>`;if(m==='vat')p.innerHTML=`<div class="tool-grid">${field('Amount','vatAmount',100)}${field('VAT %','vatRate',24)}</div><div id="toolOutput" class="tool-result">Choose an action.</div><div class="tool-grid"><button class="tool-action" data-tool-action="vat-add">Add VAT</button><button class="tool-action" data-tool-action="vat-remove">Remove VAT</button></div>`;if(m==='units'){p.innerHTML=`<div class="tool-grid">${field('Value','unitValue',5)}<div class="tool-field"><label>Category</label><select id="unitCategory"><option>length</option><option>weight</option><option>volume</option><option>speed</option><option>temperature</option></select></div><div class="tool-field"><label>From</label><select id="unitFrom"></select></div><div class="tool-field"><label>To</label><select id="unitTo"></select></div></div><div id="toolOutput" class="tool-result">Choose units and convert.</div><button class="tool-action" data-tool-action="units">Convert</button>`;populateUnits()}}
function populateUnits(){const n=Object.keys(units[$('#unitCategory').value]);$('#unitFrom').innerHTML=n.map(x=>`<option>${x}</option>`).join('');$('#unitTo').innerHTML=n.map(x=>`<option>${x}</option>`).join('');if(n[1])$('#unitTo').selectedIndex=1}function temp(v,f,t){const c=f==='C'?v:f==='F'?(v-32)*5/9:v-273.15;return t==='C'?c:t==='F'?c*9/5+32:c+273.15}
async function toolResult(v,label,explanation){if(!Number.isFinite(v))return;expression=raw(v);lastResult=v;lastExplanation=explanation;display(v);await saveHistory({expression:label,result:fmt(v),explanation})}
async function perform(a){if(a==='fuel'){const d=+$('#fuelDistance').value,c=+$('#fuelConsumption').value,p=+$('#fuelPrice').value,l=d*c/100,cost=l*p;const x={summary:'Fuel consumption tells us how many litres are used for every 100 km.',steps:[step('Fuel used',`${fmt(d)} km × ${fmt(c)} ÷ 100`,`${fmt(l)} L`),step('Fuel cost',`${fmt(l)} L × €${fmt(p)} / L`,`€${fmt(cost)}`),step('Cost per kilometre',`€${fmt(cost)} ÷ ${fmt(d)} km`,`€${fmt(cost/d)} / km`)]};$('#toolOutput').innerHTML=`Fuel used: <strong>${fmt(l)} L</strong><br>Total cost: <strong>€${fmt(cost)}</strong><br>Cost per km: <strong>€${fmt(cost/d)}</strong>`;await toolResult(cost,`${fmt(d)} km × ${fmt(c)} L/100 km × €${fmt(p)}/L`,x)}else if(a==='energy'){const w=+$('#energyPower').value,h=+$('#energyHours').value,d=+$('#energyDays').value,r=+$('#energyRate').value,k=w/1000*h*d,cost=k*r;const x={summary:'Watts are converted to kilowatts because electricity is billed in kWh.',steps:[step('Convert watts',`${fmt(w)} W ÷ 1,000`,`${fmt(w/1000)} kW`),step('Energy used',`${fmt(w/1000)} kW × ${fmt(h)} h/day × ${fmt(d)} days`,`${fmt(k)} kWh`),step('Electricity cost',`${fmt(k)} kWh × €${fmt(r)} / kWh`,`€${fmt(cost)}`)]};$('#toolOutput').innerHTML=`Energy: <strong>${fmt(k)} kWh</strong><br>Total cost: <strong>€${fmt(cost)}</strong>`;await toolResult(cost,`${fmt(w)} W × ${fmt(h)} h/day × ${fmt(d)} days × €${fmt(r)}/kWh`,x)}else if(a==='vat-add'||a==='vat-remove'){const n=+$('#vatAmount').value,r=+$('#vatRate').value/100,res=a==='vat-add'?n*(1+r):n/(1+r),v=a==='vat-add'?res-n:n-res;const x=a==='vat-add'?{summary:`${r*100}% VAT is added to the original amount.`,steps:[step('Calculate VAT',`${fmt(n)} × ${r*100} ÷ 100`,fmt(v)),step('Add VAT',`${fmt(n)} + ${fmt(v)}`,fmt(res))]}:{summary:'When an amount already includes VAT, divide by 1 + the VAT rate to find the original price.',steps:[step('Remove VAT',`${fmt(n)} ÷ (1 + ${r})`,fmt(res)),step('VAT amount',`${fmt(n)} − ${fmt(res)}`,fmt(Math.abs(v)))]};$('#toolOutput').innerHTML=`Result: <strong>€${fmt(res)}</strong><br>VAT: <strong>€${fmt(Math.abs(v))}</strong>`;await toolResult(res,`€${fmt(n)} ${a==='vat-add'?'+ VAT':'including VAT at '+r*100+'%'}`,x)}else if(a==='units'){const v=+$('#unitValue').value,c=$('#unitCategory').value,f=$('#unitFrom').value,t=$('#unitTo').value,res=c==='temperature'?temp(v,f,t):v*units[c][f]/units[c][t];const x={summary:'The value is converted using the relationship between the two units.',steps:[step('Convert',`${fmt(v)} ${f} → ${t}`,`${fmt(res)} ${t}`)]};$('#toolOutput').innerHTML=`<strong>${fmt(res)} ${t}</strong>`;await toolResult(res,`${fmt(v)} ${f} → ${t}`,x)}}
async function refreshHistory(){const items=await historyItems();$('#historyList').innerHTML=items.length?items.map(i=>`<div class="history-item"><button class="history-main" data-id="${i.id}"><div class="history-expression">${esc(i.expression)}</div><div class="history-result">${esc(i.result)}</div></button><button class="history-delete" data-id="${i.id}" aria-label="Delete calculation">×</button></div>`).join(''):'<div class="empty">No calculations yet.</div>'}
function openAuth(mode='login'){authMode=mode;$('#authModal').classList.remove('hidden');$('#authTitle').textContent=mode==='login'?'Sign in':'Create account';$('#loginTab').classList.toggle('active',mode==='login');$('#registerTab').classList.toggle('active',mode==='register');$('#authSubmit').textContent=mode==='login'?'Sign in':'Create account';$('#authMessage').textContent='';$('#authPassword').value=''}
async function submitAuth(e){e.preventDefault();try{const d=await api(authMode==='login'?'/api/login':'/api/register',{method:'POST',body:JSON.stringify({username:$('#authUsername').value.trim(),password:$('#authPassword').value})});authUser=d.user;$('#authModal').classList.add('hidden');await syncLocalToAccount();updateAccountButton();await refreshHistory()}catch(err){$('#authMessage').textContent=err.message}}
$$('.key').forEach(b=>b.onclick=()=>{const a=b.dataset.action,v=b.dataset.value;a==='clear'?clearAll():a==='backspace'?back():a==='equals'?calculate():append(v)});$$('.tab').forEach(t=>t.onclick=()=>{$$('.tab').forEach(x=>x.classList.remove('active'));t.classList.add('active');currentMode=t.dataset.mode;renderTool(currentMode);invalidateExplanation()});$('#toolPanel').onclick=e=>{if(e.target.dataset.toolAction)perform(e.target.dataset.toolAction)};$('#toolPanel').onchange=e=>{if(e.target.id==='unitCategory')populateUnits()};
$('#howButton').onclick=()=>showHow();$('#closeHow').onclick=()=>$('#howPanel').classList.add('hidden');$('#historyButton').onclick=async()=>{$('#historyPanel').classList.toggle('hidden');if(!$('#historyPanel').classList.contains('hidden'))await refreshHistory()};$('#clearHistory').onclick=async()=>{if(confirm('Delete all calculation history?'))await wipeHistory()};
$('#historyList').onclick=async e=>{const d=e.target.closest('.history-delete');if(d){await removeHistory(d.dataset.id);return}const b=e.target.closest('.history-main');if(b){const i=(await historyItems()).find(x=>String(x.id)===b.dataset.id);if(i){expression=i.expression;lastResult=Number(String(i.result).replace(/,/g,''));lastExplanation=i.explanation;display(lastResult);showHow()}}};
$('#copyButton').onclick=async()=>{if(lastResult===null)return;try{await navigator.clipboard.writeText(String(lastResult));$('#copyButton').textContent='Copied';setTimeout(()=>$('#copyButton').textContent='Copy result',1000)}catch{}};$('#themeButton').onclick=()=>document.body.classList.toggle('light');
$('#accountButton').onclick=async()=>{if(authUser){await api('/api/logout',{method:'POST'}).catch(()=>{});authUser=null;updateAccountButton();await refreshHistory()}else openAuth()};$('#closeAuth').onclick=()=>$('#authModal').classList.add('hidden');$('#loginTab').onclick=()=>openAuth('login');$('#registerTab').onclick=()=>openAuth('register');$('#authForm').onsubmit=submitAuth;
document.addEventListener('keydown',e=>{if(e.target.matches('input,select'))return;if(e.key==='Enter')calculate();else if(e.key==='Backspace')back();else if(/[0-9.+\-*/%]/.test(e.key))append(e.key)});checkAuth();display(0);renderTool('calc');
