const $ = s => document.querySelector(s), $$ = s => [...document.querySelectorAll(s)];
let expression='', lastResult=null, currentMode='calc', user=null, authMode='login';
const fmt=v=>Number.isFinite(v)?new Intl.NumberFormat(undefined,{maximumFractionDigits:10}).format(Math.abs(v)<1e-12?0:v):'Error';
const raw=v=>String(Number(v.toPrecision(12)));
const esc=v=>String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function tokenize(s){s=s.replace(/[€$£¥₹]/g,'').replace(/,/g,'');let a=[],i=0;while(i<s.length){let c=s[i];if(/\s/.test(c)){i++;continue}if(/[0-9.]/.test(c)){let j=i,d=0;while(j<s.length&&/[0-9.]/.test(s[j])){if(s[j]==='.')d++;if(d>1)throw Error();j++}let n=Number(s.slice(i,j));if(!Number.isFinite(n))throw Error();a.push({t:'n',v:n});i=j;continue}if('+-*/()'.includes(c)){a.push({t:c});i++;continue}if(c==='%'){a.push({t:'%'});i++;continue}throw Error()}return a}
function evaluate(s){let t=tokenize(s),p=0;function pri(){let x=t[p];if(!x)throw Error();if(x.t==='n'){p++;let n={v:x.v,p:false};if(t[p]?.t==='%'){p++;n={v:x.v/100,p:true}}return n}if(x.t==='('){p++;let n=add();if(t[p]?.t!==')')throw Error();p++;if(t[p]?.t==='%'){p++;return{v:n.v/100,p:true}}return n}if(x.t==='-'){p++;let n=pri();return{v:-n.v,p:n.p}}throw Error()}function mul(){let l=pri();while(t[p]&&['*','/'].includes(t[p].t)){let o=t[p++].t,r=pri();if(o==='/'&&r.v===0)throw Error();l={v:o==='*'?l.v*r.v:l.v/r.v,p:false}}return l}function add(){let l=mul();while(t[p]&&['+','-'].includes(t[p].t)){let o=t[p++].t,r=mul(),n=r.p?l.v*r.v:r.v;l={v:o==='+'?l.v+n:l.v-n,p:false}}return l}let r=add();if(p!==t.length)throw Error();return r.v}
function display(v=null){$('#expression').textContent=expression;$('#result').textContent=v===null?(expression?'…':'0'):fmt(v)}
async function api(path,opt={}){let r=await fetch(path,{credentials:'same-origin',headers:{'Content-Type':'application/json',...(opt.headers||{})},...opt}),d={};try{d=await r.json()}catch{}if(!r.ok)throw Error(d.error||'Request failed');return d}
async function loadMe(){try{let d=await api('/api/me');user=d.user;account();await history()}catch{}}
function account(){$('#accountButton').textContent=user?user.username:'Sign in'}
function openAuth(mode='login'){authMode=mode;$('#authModal').classList.remove('hidden');$('#authError').textContent='';$$('.auth-tab').forEach(x=>x.classList.toggle('active',x.dataset.authMode===mode));$('#authTitle').textContent=mode==='login'?'Sign in':'Create account';$('#authSubmit').textContent=mode==='login'?'Sign in':'Create account';$('#authPassword').value=''}
async function auth(){try{let d=await api(authMode==='login'?'/api/login':'/api/register',{method:'POST',body:JSON.stringify({username:$('#authUsername').value.trim(),password:$('#authPassword').value})});user=d.user;$('#authModal').classList.add('hidden');account();history()}catch(e){$('#authError').textContent=e.message}}
async function history(){let l=$('#historyList');if(!user){l.innerHTML='<div class="empty">Sign in to keep history synced across devices.</div>';return}try{let d=await api('/api/history');l.innerHTML=d.items.length?d.items.map(i=>`<div class="history-item"><div><div class="history-expression">${esc(i.expression)}</div><div class="history-result">${esc(i.result)}</div></div><button class="history-delete" data-id="${i.id}">×</button></div>`).join(''):'<div class="empty">No calculations yet.</div>'}catch{l.innerHTML='<div class="empty">Could not load history.</div>'}}
async function save(e,r,label=''){if(user)try{await api('/api/history',{method:'POST',body:JSON.stringify({expression:e,result:r,label})});history()}catch{}}
function calculate(){if(!expression.trim())return;try{let v=evaluate(expression);lastResult=v;display(v);save(expression,fmt(v))}catch{$('#result').textContent='Error';lastResult=null}}
function append(v){if(v==='.'&&/(^|[+\-*/(])\s*\d*\.\d*$/.test(expression))return;if(v==='%'&&!/[0-9)]$/.test(expression))return;if('+-*/'.includes(v)){if(!expression&&v!=='-')return;if(/[+\-*/]$/.test(expression))expression=expression.slice(0,-1)+v}expression+=v;display()}
function clearAll(){expression='';lastResult=null;display(0)}function back(){expression=expression.slice(0,-1);display()}
function toolResult(v,label){if(!Number.isFinite(v))return;expression=raw(v);lastResult=v;display(v);save(label,fmt(v),label)}
const units={length:{m:1,km:1000,mi:1609.344,ft:.3048,in:.0254,yd:.9144},weight:{kg:1,g:.001,lb:.45359237,oz:.028349523125},volume:{L:1,mL:.001,gal:3.785411784,qt:.946352946,cup:.2365882365},speed:{'km/h':1,mph:1.609344,'m/s':3.6,knot:1.852},temperature:{C:1,F:1,K:1}};
const field=(l,id,v,t='number')=>`<div class="tool-field"><label>${l}</label><input id="${id}" type="${t}" value="${v}"></div>`;
function renderTool(m){let p=$('#toolPanel');p.classList.toggle('hidden',m==='calc');if(m==='calc'){p.innerHTML='';return}if(m==='fuel')p.innerHTML=`<div class="tool-grid">${field('Distance','fuelDistance',100)}${field('Consumption (L/100 km)','fuelConsumption',7)}${field('Fuel price / L','fuelPrice',1.8)}</div><div id="toolOutput" class="tool-result">Enter values and calculate.</div><button class="tool-action" data-tool-action="fuel">Calculate fuel cost</button>`;if(m==='energy')p.innerHTML=`<div class="tool-grid">${field('Power (W)','energyPower',100)}${field('Hours / day','energyHours',8)}${field('Days','energyDays',30)}${field('Electricity price / kWh','energyRate',.2)}</div><div id="toolOutput" class="tool-result">Enter values and calculate.</div><button class="tool-action" data-tool-action="energy">Calculate electricity cost</button>`;if(m==='vat')p.innerHTML=`<div class="tool-grid">${field('Amount','vatAmount',100)}${field('VAT %','vatRate',24)}</div><div id="toolOutput" class="tool-result">Choose an action.</div><div class="tool-grid"><button class="tool-action" data-tool-action="vat-add">Add VAT</button><button class="tool-action" data-tool-action="vat-remove">Remove VAT</button></div>`;if(m==='units'){p.innerHTML=`<div class="tool-grid">${field('Value','unitValue',5)}<div class="tool-field"><label>Category</label><select id="unitCategory"><option>length</option><option>weight</option><option>volume</option><option>speed</option><option>temperature</option></select></div><div class="tool-field"><label>From</label><select id="unitFrom"></select></div><div class="tool-field"><label>To</label><select id="unitTo"></select></div></div><div id="toolOutput" class="tool-result">Choose units and convert.</div><button class="tool-action" data-tool-action="units">Convert</button>`;populateUnits()}}
function populateUnits(){let n=Object.keys(units[$('#unitCategory').value]);$('#unitFrom').innerHTML=n.map(x=>`<option>${x}</option>`).join('');$('#unitTo').innerHTML=n.map(x=>`<option>${x}</option>`).join('');if(n[1])$('#unitTo').selectedIndex=1}
function temp(v,f,t){let c=f==='C'?v:f==='F'?(v-32)*5/9:v-273.15;return t==='C'?c:t==='F'?c*9/5+32:c+273.15}
function perform(a){if(a==='fuel'){let d=+fuelDistance.value,c=+fuelConsumption.value,p=+fuelPrice.value,l=d*c/100,cost=l*p;toolOutput.innerHTML=`Fuel used: <strong>${fmt(l)} L</strong><br>Total cost: <strong>€${fmt(cost)}</strong><br>Cost per km: <strong>€${fmt(cost/d)}</strong>`;toolResult(cost,`${d} km × ${c} L/100 km × €${p}/L`)}if(a==='energy'){let w=+energyPower.value,h=+energyHours.value,d=+energyDays.value,r=+energyRate.value,k=w/1000*h*d,cost=k*r;toolOutput.innerHTML=`Energy: <strong>${fmt(k)} kWh</strong><br>Total cost: <strong>€${fmt(cost)}</strong>`;toolResult(cost,`${w} W × ${h} h/day × ${d} days × €${r}/kWh`)}if(a==='vat-add'||a==='vat-remove'){let n=+vatAmount.value,r=+vatRate.value/100,res=a==='vat-add'?n*(1+r):n/(1+r),v=a==='vat-add'?res-n:n-res;toolOutput.innerHTML=`Result: <strong>€${fmt(res)}</strong><br>VAT: <strong>€${fmt(Math.abs(v))}</strong>`;toolResult(res,`€${n} ${a==='vat-add'?'+':'including'} ${r*100}% VAT`)}if(a==='units'){let v=+unitValue.value,c=unitCategory.value,f=unitFrom.value,t=unitTo.value,res=c==='temperature'?temp(v,f,t):v*units[c][f]/units[c][t];toolOutput.innerHTML=`<strong>${fmt(res)} ${t}</strong>`;toolResult(res,`${v} ${f} → ${t}`)}}

$$('.key').forEach(b=>b.onclick=()=>{let a=b.dataset.action,v=b.dataset.value;a==='clear'?clearAll():a==='backspace'?back():a==='equals'?calculate():append(v)});$$('.tab').forEach(t=>t.onclick=()=>{$$('.tab').forEach(x=>x.classList.remove('active'));t.classList.add('active');currentMode=t.dataset.mode;renderTool(currentMode)});$('#toolPanel').onclick=e=>e.target.dataset.toolAction&&perform(e.target.dataset.toolAction);$('#toolPanel').onchange=e=>e.target.id==='unitCategory'&&populateUnits();$('#historyButton').onclick=()=>$('#historyPanel').classList.toggle('hidden');$('#clearHistory').onclick=async()=>{if(user&&confirm('Delete all of your calculation history?')){await api('/api/history',{method:'DELETE'});history()}else if(!user)openAuth()};$('#historyList').onclick=e=>{let b=e.target.closest('.history-delete');if(b)api('/api/history/'+b.dataset.id,{method:'DELETE'}).then(history)};$('#copyButton').onclick=async()=>{try{await navigator.clipboard.writeText($('#result').textContent);$('#copyButton').textContent='Copied';setTimeout(()=>$('#copyButton').textContent='Copy result',900)}catch{}};$('#accountButton').onclick=async()=>{if(!user)return openAuth();if(confirm('Sign out?')){await api('/api/logout',{method:'POST',body:'{}'});user=null;account();history()}};$('#authSubmit').onclick=auth;$('#closeAuth').onclick=()=>$('#authModal').classList.add('hidden');$$('.auth-tab').forEach(x=>x.onclick=()=>openAuth(x.dataset.authMode));$('#authModal').onclick=e=>e.target===e.currentTarget&&e.currentTarget.classList.add('hidden');$('#themeButton').onclick=()=>document.body.classList.toggle('light');document.onkeydown=e=>{if(['INPUT','SELECT'].includes(document.activeElement.tagName))return;if(e.key==='Enter')calculate();else if(e.key==='Backspace')back();else if('0123456789.+-*/%()'.includes(e.key))append(e.key)};
renderTool('calc');loadMe();
