services:
  ultimate-calculator:
    image: ghcr.io/leothegreat777/ultimate-calculator:latest
    pull_policy: always
    container_name: ultimate-calculator
    ports:
      - "48123:80"
    restart: unless-stopped
